apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      labels:
        app: myreactapp
    spec:
      containers:
      - name: myreactapp-site
        image: prabhurajang/myreactapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myreactapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myreactapp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30004